# Generated by Django 4.2.16 on 2024-12-01 17:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file_name', models.CharField(max_length=30)),
                ('file_type', models.CharField(choices=[('document', 'Document'), ('avatar', 'Avatar')], max_length=20)),
                ('file_mime', models.CharField(max_length=10)),
                ('file_base64', models.TextField()),
                ('profile_id', models.UUIDField()),
                ('project_id', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('profile_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('project_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('profile_type', models.CharField(choices=[('anonymous', 'Anonymous'), ('person', 'Person')], max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_date', models.DateField()),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('contact_phone', models.JSONField()),
                ('contact_email', models.JSONField()),
                ('file_field', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
