# Generated by Django 4.2.16 on 2024-12-25 17:51

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.utils.timezone
import user_profile.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-meta__internal_id']},
        ),
        migrations.RenameField(
            model_name='file',
            old_name='file_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='file',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='file',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='file',
            name='profile_id',
        ),
        migrations.AddField(
            model_name='file',
            name='account_id',
            field=models.UUIDField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='data',
            field=models.JSONField(default=user_profile.models.data_default_value, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='meta',
            field=models.JSONField(default=user_profile.models.meta_default_value),
        ),
        migrations.AddField(
            model_name='file',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='object_code',
            field=models.CharField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='file',
            name='object_item',
            field=models.UUIDField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='object_type',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='user_id',
            field=models.UUIDField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='account_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='file',
            name='project_id',
            field=models.UUIDField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='project_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddIndex(
            model_name='file',
            index=django.contrib.postgres.indexes.GinIndex(fields=['data'], name='files_data_gin'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['object_item'], name='files_object_item_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['created_date'], name='files_cr_date_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['modified_date'], name='files_mod_date_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['object_item', 'object_type'], name='files_o_item_type_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['project_id', 'account_id', 'user_id'], name='files_p_a_u_ids_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['account_id', 'user_id'], name='files_a_u_ids_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['user_id'], name='files_user_id_idx'),
        ),
    ]
