# Generated by Django 4.2.16 on 2024-12-25 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_file_options_rename_file_id_file_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_id',
            new_name='user_id',
        ),
    ]
