# Generated by Django 4.2.16 on 2024-12-25 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_rename_profile_id_userprofile_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_base64',
        ),
        migrations.RemoveField(
            model_name='file',
            name='file_mime',
        ),
    ]
