# Generated by Django 4.2.16 on 2024-12-27 14:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_remove_file_file_base64_remove_file_file_mime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='account_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='project_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4),
        ),
    ]
