# Generated by Django 4.2.16 on 2024-12-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_alter_userprofile_account_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='object_code',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
